### ISSUE TITLE
openwrt主机型号为?

### ISSUE THREAD

**Issue by pangfeng161** [1715173329/immortalwrt#537]
openwrt主机型号为?,这个能解决吗

**Comment by 1715173329** [comment]
设备

**Comment by pangfeng161** [comment]
> 设备为何

1. 设备j3160, @``

- [ ] 

- [ ] ### ****

**Comment by pangfeng161** [comment]
> 设备为何

主机j3160刷其他固件显示正常
![QQ截图20220116233532](https://user-images.githubusercontent.com/64266231/149666816-597e7636-4cfc-452c-944d-50cb65a286a6.png)
